### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by rlambert27** [MattHirschfelt/Nest-Extended#12]
Hi Matt,

Is your script still working? For some reason mine is no longer collecting any data?

http://mynestreport.com/

Just wondering, thanks!

Roch

**Comment by costerwi** [comment]
Mine is working but I needed to update the Nest library #10 .  I've merged my PRs here if you'd like to try it: https://github.com/costerwi/Nest-Extended

**Comment by rlambert27** [comment]
Thanks, i'll try this week to update the script.
