### ISSUE TITLE
Errors returned by nest-get-data.php

### ISSUE THREAD

**Issue by jase31** [MattHirschfelt/Nest-Extended#3]
nest-get-data.php is populating the db, but returns the following errors. Index.php shows headers only but no graph boxes. 

Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in C:\wamp\www\resources\utils\nest-get-data.php on line 16
Call Stack

1	0.0020	274560	{main}( )	..\nest-get-data.php:0
2	0.0090	528888	mysql_connect ( )	..\nest-get-data.php:16

( ! ) Notice: Undefined property: stdClass::$location in C:\wamp\www\resources\libs\nest\nest.class.php on line 139
Call Stack

1	0.0020	274560	{main}( )	..\nest-get-data.php:0
2	0.0390	657712	Nest->getUserLocations( )	..\nest-get-data.php:23

( ! ) Notice: Undefined property: stdClass::$away_timestamp in C:\wamp\www\resources\libs\nest\nest.class.php on line 145
Call Stack

1	0.0020	274560	{main}( )	..\nest-get-data.php:0
2	0.0390	657712	Nest->getUserLocations( )	..\nest-get-data.php:23

( ! ) Notice: Undefined property: stdClass::$humidity in C:\wamp\www\resources\utils\nest-get-data.php on line 74
Call Stack

1	0.0020	274560	{main}( )	..\nest-get-data.php:0

( ! ) Notice: Undefined property: stdClass::$humidifier in C:\wamp\www\resources\utils\nest-get-data.php on line 74
Call Stack

1	0.0020	274560	{main}( )	..\nest-get-data.php:0

**Comment by patfee** [comment]
Hi,
i receive an error as follows:
Fatal error: Uncaught exception 'RuntimeException' with message 'Error: HTTP request to https://home.nest.com/user/login returned an error: error setting certificate verify locations: CAfile: /var/services/tmp/cacert.pem CApath: none' in /volume1/web/nest/resources/libs/nest/nest.class.php:690 Stack trace: #0 /volume1/web/nest/resources/libs/nest/nest.class.php(622): Nest->doRequest('POST', 'https://home.ne...', Array) #1 /volume1/web/nest/resources/libs/nest/nest.class.php(573): Nest->doPOST('https://home.ne...', Array) #2 /volume1/web/nest/resources/libs/nest/nest.class.php(99): Nest->login() #3 /volume1/web/nest/resources/utils/nest-get-data.php(20): Nest->__construct() #4 {main} thrown in /volume1/web/nest/resources/libs/nest/nest.class.php on line 690

it is the first time installation on my synology nas

nothing is inserted in the database too

thanks for your assistance

**Comment by costerwi** [comment]
The undefined property errors should be improved by updating the Nest library in #10.
The warning about mysql should be fixed in #9 by upgrading to mysqli.
